[build]
# The index HTML file to drive the bundling process.
target = "./drophub-front/static/index.html"
# The output dir for all final assets.
dist = "./dist"

[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
watch = ["./"]

# Paths to ignore.
ignore = [
    "./drophub-front/node_modules",
    "./drophub-front/package-lock.json",
]