name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install cargo-nextest
      uses: taiki-e/install-action@nextest

    - uses: actions/setup-node@v3
    - name: Install trunk
      uses: jetli/trunk-action@v0.1.0
      with:
        version: 'latest'
    - name: Install rust toolchain (wasm)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true
        profile: minimal
    - name: Build (drophub-front)
      run: trunk build
          

    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Build (drophub)
      run: cargo build -p drophub --all-features --verbose
    - name: Build (drophub-back)
      run: cargo build -p drophub-back --verbose
    - name: Test (drophub)
      run: cargo nextest run -p drophub --all-features --verbose
    - name: Test (drophub-back)
      run: cargo nextest run -p drophub-back --verbose
    - name: Clippy (drophub)
      run: cargo clippy -p drophub --all-features --verbose
    - name: Clippy (drophub-back)
      run: cargo clippy -p drophub-back --verbose
